version: "3.9"

services:
  app:
    build: .
    ports:
      - "8080:8080"
    networks:
      - local
    env_file:
      - .env
    depends_on:
      - mongo
    restart: always
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - local
    volumes:
      - "mongo-data:/var/lib/mongo/data"
    restart: always

networks:
  local:
    driver: bridge

volumes:
  mongo-data: